### PR TITLE
"Should" library in docs should be "Shouldly"

### PR DESCRIPTION
**Pull request by mikecole**

### CODE REVIEW

**Comment by scichelli** [comment]
Oh, I can see how that's confusing, and the Should library is surprisingly hard to google for. @plioi, do you know, is this the main repo for the library (i.e, Hexter didn't make a GitHub organization for it)? https://github.com/erichexter/Should

If that's the right link, then @mikecole, that might be a way to clear up the confusion: linking to the `Should` repo to clearly distinguish it from the `Shouldly` library.

**Comment by plioi** [comment]
Yeah, @scichelli, that's the main repo.

**Comment by mikecole** [comment]
You are correct. My mistake. I was not aware of the Should library.

**Comment by plioi** [comment]
I've updated that page to link to the Should library.

**Pull request closed without merging**
